### ISSUE TITLE
Error occurs when npm run start

### ISSUE THREAD

**Issue by yogakurniawan** [supercycle91/isomorphic-demo#2]
Hi supercycle91,

First of all, I am very curious about all universal/isomorphic React project and I am grateful I can try out your project.
However, I got issue where after I got all dependencies installed and then I run using command npm run start, I got this error.

> Module build failed: ReferenceError: Unknown plugin \"transform-class-properties\" specified in \"/Users/Kafilah/experiment/.babelrc\" at 0, attempted to resolve relative to \"/Users/Kafilah/experiment\"\n    at /Users/Kafilah/experiment/isomorphic-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17\n    at Array.map (native)\n    at Function.normalisePlugins (/Users/Kafilah/experiment/isomorphic-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)\n    at OptionManager.mergeOptions (/Users/Kafilah/experiment/isomorphic-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)\n    at OptionManager.init (/Users/Kafilah/experiment/isomorphic-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)\n    at File.initOptions (/Users/Kafilah/experiment/isomorphic-demo/node_modules/babel-core/lib/transformation/file/index.js:212:65)\n    at new File (/Users/Kafilah/experiment/isomorphic-demo/node_modules/babel-core/lib/transformation/file/index.js:135:24)\n    at Pipeline.transform (/Users/Kafilah/experiment/isomorphic-demo/node_modules/babel-core/lib/transformation/pipeline.js:46:16)\n    at transpile (/Users/Kafilah/experiment/isomorphic-demo/node_modules/babel-loader/lib/index.js:46:20)\n    at Object.module.exports (/Users/Kafilah/experiment/isomorphic-demo/node_modules/babel-loader/lib/index.js:163:20)

Could you please help? I have no idea what causing this problem
Thank you.

**Comment by supercycle91** [comment]
"transform-class-properties" is not a direct dependency of my project but what I found is that it is a dependency of "react-helmet". "react-helmet" is used in my project and my first approach would be to reinstall "react-helmet". I am not getting this error on my end when I clone, run "npm install", and run "npm start"
